### ISSUE TITLE
cant redeem code

### ISSUE THREAD

**Issue by yeci226** [wavyflow/hoyoapi#91]
title

**Comment by jokelbaf** [comment]
What is the problem? Which game? Code? Give more context

**Comment by MurasakiNX** [comment]
I think it's about Honkai Star Rail, because it returns an error

"System busy. Please try again later. (Error code -1048)"

**Comment by jokelbaf** [comment]
> I think it's about Honkai Star Rail, because it returns an error
> 
> "System busy. Please try again later. (Error code -1048)"

I see. The problem is that url for HSR redemption is different from Genshin one.

For star rail:
`https://sg-hkrpg-api.hoyoverse.com/common/apicdkey/api/webExchangeCdkey`

For genshin:
`https://sg-hk4e-api.hoyolab.com/common/apicdkey/api/webExchangeCdkey`

You can manually fix that by adding some _"if else"_ logic for url depending on `game` in `module/redeem/redeem.js` file.

**Comment by jokelbaf** [comment]
Here is an example of the temporary fix:

```javascript
...
const url = this.game === "hkrpg_global" ? "https://sg-hkrpg-api.hoyoverse.com/common/apicdkey/api/webExchangeCdkey" : "https://sg-hk4e-api.hoyolab.com/common/apicdkey/api/webExchangeCdkey";
const { response } = await this.request.send(url, "GET", 0);
return response;
```

I hope either @vermaysha or @wavyflow will finally pay attention and fix tons of bugs in their library...
